changelog:
  exclude:
    labels:
    - "ignore for release"
    - codebase
    - documentation
    - duplicate
    - suggestion
  categories:
  - title: Changes
    labels:
    - enhancement
    - performance
  - title: Bug fixes
    labels:
    - bug
