#   ____  _      _                     _        _   
#  |  _ \(_) ___| | ___ __   ___   ___| | _____| |_ 
#  | |_) | |/ __| |/ / '_ \ / _ \ / __| |/ / _ \ __|
#  |  __/| | (__|   <| |_) | (_) | (__|   <  __/ |_ 
#  |_|   |_|\___|_|\_\ .__/ \___/ \___|_|\_\___|\__|
#                    |_|                            

pickpocketingEnabled: true

# Items that cannot be pickpocketed.
#
# Use '*' to disabled every item.
# Use '-' to invert an item e.g. '- "-shulkur_box"'. This will enable the shulkur_box
disabledItems:
  - "shulkur_box"
  - "bundle"

money:
  # Whether players have a change of stealing money
  # when pickpocketing.
  canBeStolen: false

  # The percentage of money to be stolen from the other
  # players balance. Default is 2.5% of the other
  # persons balance.
  percentageToSteal: 0.025

# Configuration settings for Towny
towny:
  # Whether players can steal from players in a different town then them.
  foreignTownTheft: true

  # Whether players can steal from players in their town.
  sameTownTheft: true