main: logan.pickpocket.main.PickpocketPlugin
name: Pickpocket
version: 3.0
author: escape9179
api-version: '1.19'
softdepend: [ Vault, WorldGuard, WorldEdit, Essentials, Towny ]
commands:
  pickpocket:
    aliases: pp
    description: Display help information for PickPocket.
    permission: pickpocket.use
permissions:
  pickpocket.use:
    description: Basic access to plugin features.
    default: true
  pickpocket.admin.toggle:
    description: Toggle server-wide pickpocketing.
  pickpocket.skill.set:
    description: Set one of your pickpocket skill levels.
  pickpocket.skill.view:
    description: View your pickpocket skill levels.
    default: true
  pickpocket.debug:
    description: Access to debug commands.
    children:
      pickpocket.debug.giverandom: true