main: logan.pickpocket.main.PickpocketPlugin
name: Pickpocket
version: 3.0-SNAPSHOT
author: escape9179
api-version: "1.17"
softdepend: [ Vault, WorldGuard, WorldEdit, Essentials, Towny ]
commands:
  pickpocket:
    aliases: pp
    description: Display help information for PickPocket.
    permission: pickpocket.use
